- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes
  become: yes

- name: Upgrade all packages to the latest version
  apt: 
    name: "*"
    state: latest
  become: yes

- name: Adding alias to .bashrc
  lineinfile:
    path: /home/{{ user }}/.bashrc
    line: alias hh='hostname'
    insertafter: alias.*

- name: Install useful packages
  apt: name={{item}} state=latest
  with_items:
       - htop
       - vim
       - git
  become: yes

- name: Add an apt key by id from a keyserver
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google Chrome repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Install Google Chrome
  apt: 
    name: google-chrome-stable 
    state: latest
  become: yes


    