- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes
  become: yes

- name: Upgrade all packages to the latest version
  apt: 
    name: "*"
    state: latest
  become: yes

- name: Install useful packages
  apt: name={{item}} state=latest
  with_items:
       - htop
       - vim
       - git
  become: yes
