- name: Add an apt key by id from a keyserver
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

# - name: Add microsoft repository
#   apt_repository:
#     repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
#     state: present

- name: Install visualstudio code
  apt: name=code state=latest