- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Add user to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes

- name: Create custom docker network
  docker_network:
    name: docker
    ipam_config:
      - subnet: 10.0.0.0/24
        gateway: 10.0.0.1
        iprange: 10.0.0.0/24

- name: pull portainer image
  docker_image:
    name: portainer/portainer
    source: pull

- name: Create portainer container
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started
    restart_policy: always
    restart: no
    networks:
      - name: docker
        ipv4_address: 10.0.0.2
    ports:
     - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

- name: Create watchtower container
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    state: started
    restart_policy: always
    restart: no
    networks:
      - name: docker
        ipv4_address: 10.0.0.4
    ports:
      - "444:3443"
      - "8081:3080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30