- hosts: localhost
  become: true

  roles:
    - { role: general, tags: ['general'] }
    - { role: docker, tags: ['docker'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    - { role: spotify, tags: ['spotify'] }
    - { role: jenkins, tags: ['jenkins', 'docker'] }
    - { role: customise_ui, tags: ['ui'] }
